name: "Autosend"

on:
  push: 
    branches: main
  schedule: 
    - cron: '25 09 * * *' # 每天9点25分自动执行
  workflow_dispatch:

jobs:
  autosend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send GroupMe message via Curl
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"bot_id\": \"${{ secrets.GM_BOT_ID }}\", \"text\": \"Never say die!\"}" \
          https://api.groupme.com/v3/bots/post

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 6
